zk1:
  image: jplock/zookeeper:3.4.6

mesos-master:
  image: containersol/mesos-master:0.26.0-0.2.145.ubuntu1404
  ports:
    - "5050:5050"
  links:
    - "zk1:zookeeper1"
  environment:
    MESOS_LOG_DIR: /var/log
    MESOS_CLUSTER: localmesos
    MESOS_ZK: zk://zookeeper1:2181/mesos
    MESOS_HOSTNAME: 192.168.59.103
    MESOS_WORK_DIR: /var/lib/mesos
    MESOS_QUORUM: 1


mesos-agent:
  image: containersol/mesos-agent:0.26.0-0.2.145.ubuntu1404
  ports:
    - "5051"
  links:
    - "zk1:zookeeper1"
    - "mesos-master"
  pid: "host"
  environment:
    MESOS_MASTER: zk://zookeeper1:2181/mesos
    MESOS_ISOLATOR: "cgroups/cpu,cgroups/mem"
    MESOS_CONTAINERIZERS: "docker,mesos"
    MESOS_EXECUTOR_REGISTRATION_TIMEOUT: "5mins"
    MESOS_HOSTNAME: 192.168.59.103
    MESOS_PORT: "5051"
    MESOS_LOG_DIR: /var/log
    MESOS_ISOLATOR: "cgroups/cpu,cgroups/mem"
    MESOS_SWITCH_USER: "false"

  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /sys/fs/cgroup:/sys/fs/cgroup
